DROP TABLE IF EXISTS @SCHEMA.CSPRO2SQL_ERROR;
CREATE TABLE IF NOT EXISTS @SCHEMA.CSPRO2SQL_ERROR (
    `ID` int(11) NOT NULL AUTO_INCREMENT,
    `DICTIONARY` int(11) NOT NULL,
    `ERROR` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
    `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `CSPRO_GUID` binary(255) NOT NULL,
    `QUESTIONNAIRE` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
    `SQL_SCRIPT` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
    PRIMARY KEY (`ID`),
    KEY `dictionary_idx` (`DICTIONARY`),
    CONSTRAINT `dictionary` FOREIGN KEY (`DICTIONARY`) REFERENCES @SCHEMA.CSPRO2SQL_DICTIONARY (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

