CREATE TABLE IF NOT EXISTS @SCHEMA.DASHBOARD_USER (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MIDDLENAME` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LASTNAME` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EMAIL` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PASSWORD` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ROLE` varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  KEY `EMAIL_INDEX` (`EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO @SCHEMA.DASHBOARD_USER (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLE)
  VALUES ('Dashboard', 'Admin', 'admin@dashboard.it', '$2a$10$Yq.aC1NrfpC/grRBlc8dU.QgWG4bMvj3goJayS4DwypWXcrrHe756', 'ROLE_ADMIN');
INSERT INTO @SCHEMA.DASHBOARD_USER (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLE)
  VALUES ('Dashboard', 'Progress', 'progress@dashboard.it', '$2a$10$Yq.aC1NrfpC/grRBlc8dU.QgWG4bMvj3goJayS4DwypWXcrrHe756', 'ROLE_PROGRESS');
INSERT INTO @SCHEMA.DASHBOARD_USER (FIRSTNAME, LASTNAME, EMAIL, PASSWORD, ROLE)
  VALUES ('Dashboard', 'Analyst', 'analyst@dashboard.it', '$2a$10$Yq.aC1NrfpC/grRBlc8dU.QgWG4bMvj3goJayS4DwypWXcrrHe756', 'ROLE_ANALYST');

