DROP TABLE IF EXISTS @SCHEMA.`dashboard_status`;
CREATE TABLE IF NOT EXISTS @SCHEMA.`dashboard_status`(
  `ID` int(1) NOT NULL DEFAULT 0,
  `START_TIME` datetime DEFAULT NULL,
  `LAST_UPDATE` datetime DEFAULT NULL,
  `IS_RUNNING` int(1) NOT NULL DEFAULT 1,
    PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;