CREATE TABLE IF NOT EXISTS @SCHEMA.DASHBOARD_TOTAL (
  `SURVEY_DAY` int(3) NOT NULL,
  `TOTAL_FIELDWORK` int(11) DEFAULT NULL,
  `TOTAL_FRESHLIST` int(11) DEFAULT NULL
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

