CREATE TABLE IF NOT EXISTS @SCHEMA.TR_INDIVIDUAL_INFO (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOTAL` int(11) DEFAULT NULL,
  `AGE_AVG` decimal(6,4) DEFAULT NULL,
  `AGE_MAX` decimal(2,0) DEFAULT NULL,
  `TOTAL_MALE` int(11) NOT NULL DEFAULT '0',
  `AGE_AVG_MALE` decimal(6,4) DEFAULT NULL,
  `AGE_MAX_MALE` decimal(2,0) DEFAULT NULL,
  `TOTAL_FEMALE` int(11) NOT NULL DEFAULT '0',
  `AGE_AVG_FEMALE` decimal(6,4) DEFAULT NULL,
  `AGE_MAX_FEMALE` decimal(2,0) DEFAULT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

