CREATE TABLE IF NOT EXISTS @SCHEMA.TR_QUESTIONNAIRE_INFO (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TOTAL` int(11) DEFAULT NULL,
  `AVG_INDIVIDUAL` decimal(24,4) DEFAULT NULL,
  `AVG_INDIVIDUAL_MALE` decimal(24,4) DEFAULT NULL,
  `AVG_INDIVIDUAL_FEMALE` decimal(24,4) DEFAULT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

