CREATE TABLE IF NOT EXISTS @SCHEMA.TR_TOTAL (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `EA_FIELDWORK` int(11) DEFAULT NULL,
  `EA_FRESHLIST` int(11) DEFAULT NULL,
  `EA_EXPECTED` int(11) DEFAULT NULL,
  `HOUSEHOLD_FIELDWORK` int(11) DEFAULT NULL,
  `HOUSEHOLD_FRESHLIST` int(11) DEFAULT NULL,
  `HOUSEHOLD_EXPECTED` int(11) DEFAULT NULL,
  `UPDATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

