CREATE TABLE dbo.CSPRO2SQL_ERROR (
    ID int NOT NULL IDENTITY (1,1),
    DICTIONARY int NOT NULL,
    ERROR TEXT NOT NULL,
    DATE datetime2(0) NOT NULL DEFAULT GETDATE(),
    CSPRO_GUID binary(255) NOT NULL,
    QUESTIONNAIRE TEXT NOT NULL,
    SQL_SCRIPT TEXT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT dictionary FOREIGN KEY (DICTIONARY) REFERENCES dbo.CSPRO2SQL_DICTIONARY (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
CREATE INDEX dictionary_idx ON dbo.CSPRO2SQL_ERROR(DICTIONARY);

